---
title: "Untitled"
author: "Kenechukwu Nwosu"
date: "4/24/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}
library(ggiraph)
source(here::here("helper_scripts/misc_functions.R"))

ggpoint <- 
  cars %>% 
  ggplot(aes(dist, speed, tooltip = tooltip)) + 
  geom_point_interactive()
  
  
ggiraphpoint <- ggiraph(print(ggpoint))

ggiraphpoint %>% 
  html_webshot()
   

ggpoint <- 
  cars %>% 
  slice_sample(n = 5000, replace = TRUE) %>% 
  mutate(speed = speed + sample( (1:20000)/1000, size = n())) %>% 
  mutate(dist = dist + sample( (1:20000)/100, size = n())) %>%
  mutate(group = sample(LETTERS[1:7], size = n(), replace = TRUE)) %>% 
  mutate(tooltip = paste(dist, speed, group)) %>% 
  ggplot(aes(dist, speed, color = group, tooltip = tooltip)) + 
  geom_point_interactive()

ggiraphpoint <- ggiraph(print(ggpoint))

ggiraphpoint %>% 
  girafe_options(opts_zoom(max = 5), 
                 opts_hover()
                 )
library(plotly)

ggpoint2 <- 
  cars %>% 
  slice_sample(n = 5000, replace = TRUE) %>% 
  mutate(speed = speed + sample( (1:20000)/1000, size = n())) %>% 
  mutate(dist = dist + sample( (1:20000)/100, size = n())) %>%
  mutate(group = sample(LETTERS[1:7], size = n(), replace = TRUE)) %>% 
  mutate(tooltip = paste(dist, speed, group)) %>% 
  ggplot(aes(dist, speed, color = group, tooltip = tooltip)) + 
  geom_point()


font <- list(family = "Avenir",
              size = 15,
              color = "white")

label <- list(
  bgcolor = "#232F34",
  bordercolor = "transparent", 
  font = font
)



plotly::ggplotly(ggpoint2) %>% 
  style(hoverlabel = label, marker.color  = "#232F34") %>% 
  layout(font = font)




html <- here::here("markdown/tempfig.html") 
  png <- here::here("markdown/tempfig.png")
  
  htmlwidgets::saveWidget(chart, html)
  


  
  webshot::webshot(url = html,
                    file = png,
                    zoom = 3)

  ## regular webshot does not work for echarts4r plots
  # webshot::webshot(url = html, 
  #                   file = png, 
  #                   zoom = 3, 
  #                   vheight = vheight, 
  #                   vwidth = vwidth)
  # 
  # read back in as PNG raster
  png_out <- 
    png %>% 
    png::readPNG(info = FALSE) %>% 
    grid::rasterGrob() %>% 
    gridExtra::arrangeGrob()
  
   grid::grid.draw(png_out)
   
  
  
  html_webshot()
  
```

